### ISSUE TITLE
00 AM/PM should be 12 AM/PM when time format is set to 12 hours

### ISSUE THREAD

**Issue by DlljsCodes** [Treeki/MeteoNook#2]
This happens in the time selection drop-down when entering data and in forecast screens e.g. Overview. It really threw me off when entering data, as it doesn't match how the time is shown on the in-game clock. Happens on English (UK) language setting.
![image](https://user-images.githubusercontent.com/64469452/86365975-24ec9700-bc72-11ea-8a08-60835ea250b3.png)
Current settings:
![image](https://user-images.githubusercontent.com/64469452/86372144-b6abd280-bc79-11ea-9853-b1ac34a475e8.png)

**Comment by DlljsCodes** [comment]
Works as intended on English (US)

**Comment by Treeki** [comment]
this seems to be a Chrome/Blink bug related to me using 'hour12: true' for 12-hour times rather than 'hourCycle', I've tried to work around it and am hoping it won't break behaviour on any other setups

this comment on an entirely different project shows what seems to be a variation of the same issue, Chrome showing odd times with 'hour12: false' in en-AU when Firefox and Safari produce the correct result: https://github.com/moment/luxon/issues/675#issuecomment-640925883

**Comment by DlljsCodes** [comment]
Confirmed working on Chrome 83, with Settings set to English (UK) and 12 hours
![image](https://user-images.githubusercontent.com/64469452/87025791-c0ca5580-c1d2-11ea-88c5-41c33f171f18.png)
