### ISSUE TITLE
Recommending an impossible pattern

### ISSUE THREAD

**Issue by Ratismal** [Treeki/MeteoNook#28]
Encountered this issue where it claims that Fine02 is a possible pattern, but unless I'm missing something here it shouldn't be, as 7PM is cloudy not sunny.

![image](https://user-images.githubusercontent.com/1059362/89071336-bb74ac80-d333-11ea-8fb9-52ce6371f54c.png)
![image](https://user-images.githubusercontent.com/1059362/89071250-88cab400-d333-11ea-87e4-2f03ac46855e.png)

**Comment by Treeki** [comment]
This is not a bug. Fine02 was changed around slightly by Nintendo in 1.3.0. Rather than introduce more possible points of failure by adding an option for game version, the app accepts both the old and new versions of the pattern.

If there’s more changes to the pattern assignments in future versions, I may have to revisit that approach. For the time being, this seemed like the best compromise.
