### ISSUE TITLE
Slight anomalies in listed star times versus actual times listed in see more

### ISSUE THREAD

**Issue by thebadomenz** [Treeki/MeteoNook#38]
![Screenshot_20200911-005131_Chrome](https://user-images.githubusercontent.com/71117605/92871002-146f4000-f3ca-11ea-8e22-60489c92fa96.jpg)
![Screenshot_20200911-005159_Chrome](https://user-images.githubusercontent.com/71117605/92870987-0f11f580-f3ca-11ea-957b-6f1753c64938.jpg)
As you can see based on screenshots it lists 2:25 as a time to be on the lookout for stars but when opening the see more 2:25 is nowhere on the list. Closest being 2:18 and 2:31 respectively. 

I would like to mention that besides the slight anomaly between the two the times listed in the see more have been spot on! Creator definitely to be commended for all efforts so far!

**Comment by scottjl** [comment]
I came to report the same thing. Very strange because it usually seemed accurate but I noticed today it was way off. Seed value: 352814644. The detailed report is spot on accurate, the summary is just way off.

<img width="851" alt="Screen Shot 2020-09-16 at 8 47 11 PM" src="https://user-images.githubusercontent.com/353381/93410141-0ef87680-f85e-11ea-8e95-e6b45c696749.png">

**Comment by thebadomenz** [comment]
Want to mention seed here. It is: 1856402561

**Comment by Small-Ku** [comment]
Duplicated. See #8

**Comment by thebadomenz** [comment]
Good call! Thanks!
