### ISSUE TITLE
Weather no longer accurate as of 2020-12-25

### ISSUE THREAD

**Issue by ajf8729** [Treeki/MeteoNook#49]
My weather as of today is no longer accurate. 15:00 should be rain clouds when it's actually snowing. Seed is 194650881, northern hemisphere. It found my seed months ago and it has been 100% accurate up until today, with many light/heavy meteor showers correctly identified.

**Comment by superfucky** [comment]
Same problem, seed 1258030453. I'm supposed to have heavy snow right now and it's bright & sunny.

**Comment by ajf8729** [comment]
Interestingly, while doing some TT'ing, I ended up on 2021-01-05, and Isabelle mentioned that there would be shooting stars that night, which does match up with what my seed says for that day.

**Comment by superfucky** [comment]
Ninji replied on Twitter that there's a special event weather pattern for today not being reflected in Meteonook. Which is kinda weird cause I could've sworn it was snowing this morning, and I though event weather always meant clear skies all day, but it's a relief knowing it's still accurate into 2021 since I'm getting 2 different forecasts for next year depending on whether I view on mobile or desktop.

**Comment by ajf8729** [comment]
Cool, I'll close this issue for now and reopen it tomorrow if it still differs.
